Add Utility to Mask Hotspot data as "on-device" data
natthawk/TMOHS1-Root-Utility pull request #4
Opened 2022-03-24 22:09 UTC by parker-stephens

I've added an option to add some iptables/ip6tables rules that would mask what would normally be counted as hotspot data in the T-mobile dashboard as "on-device" data, that would allow a user on an unlimited plan to have unlimited high-speed data on the hotspot and its connected devices, instead of 5GB/40GB or whatever a plan offers at high-speed which would then be throttled to 3G. 

This would not bypass any sort of network-management or video throttling that may be apart of a customer's plan's terms. Also if a customer is on a straight-up limited data plan, this would not work either.

There's a good read-up [here](https://wirelessjoint.com/viewtopic.php?t=2752) explaining what TTL rules do.

Great work on the project btw!

2022-03-24 22:13 UTC, parker-stephens commented
I will also add, that to verify that this is working, any traceroute to an IPv4/6 address should end 1 hop after the hotspot. I've attached a picture below of what it looks like when the rule is working properly.
![image](https://user-images.githubusercontent.com/12587967/160018795-74f89a87-6b83-485a-beb0-039b1da52f39.png)

2022-04-02 02:00 UTC, natthawk requested changes
Apologies for taking so long to review this, I just happened to see it! I like the option you added, but there are just a few small things to change. All of them just affect integrating the function into the rest of the script; none of them affect the feature you added itself. Also, there's a typo or two I noticed. Great work though, and I appreciate you adding to the project!

2022-04-04 01:54 UTC, parker-stephens commented on README.md
> +- Mask data that would normally be counted as hotspot data as "on-device" data
I agree, it's a tad confusing, but I find it a little hard to explain. I specified in my last commit that it's data that would normally count towards your limited hotspot quota.

2022-04-04 01:55 UTC, natthawk approved these changes

2022-04-04 01:55 UTC, merged